# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_CRYPTO: ${{ secrets.SECRET_CRYPTO }}
      SECRET_JWT: ${{ secrets.SECRET_JWT }}
      FIRESTORE_OBJECT: ${{ secrets.FIRESTORE_OBJECT }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 3
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test
